settings:
  username: "zryyyy" # Replace with your username or comment out this line
  commit_msg: "âš¡ Update README with the recent activity"
  max_lines: 10
  readme_file: "./README.md"
  # disabled_events:
  #   - "comments"
  # url_text: "`{REPO}{ID}`"
  url_text: "`{REPO}`"
  date:
    timezone: "GMT+08:00"
    text: "Last Updated: `{DATE}`"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  comments: "ğŸ’¬ Commented on {ID} in {URL}"
  issue_opened: "â—ï¸ Opened issue {ID} in {URL}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {URL}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {URL}"
  pr_closed: "âŒ Closed PR {ID} in {URL}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {URL}"
  create_repo: "ğŸ“” Created new repository {URL}"
  fork_repo: "ğŸ”± Forked {FORK} from {URL}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {URL}"
  added_member: "ğŸ¤ Became collaborator on {URL}"
  changes_approved: "ğŸ‘ Approved {ID} in {URL}"
  changes_requested: "ğŸ”´ Requested changes in {ID} in {URL}"
  new_release: "âœŒï¸ Released {ID} in {URL}"
  new_star: "â­ Starred {URL}"
